### ISSUE TITLE
Cross-site_Scripting_(XSS)

### ISSUE THREAD

**Issue by Sajibekanti** [redaktorio/redaktor-issues#5]
vulnerable Link : https://redaktor.io/

Vulnerablity : Cross-site_Scripting_(XSS)

Steps to Reproduce  : 

1. Go To https://redaktor.io/

2. Now Click New Project

3. Now Enter this Payload In this Box In Project Name | ("><img src=1 onerror=prompt(document.domain);>) | And Click GO :) 

4. And Now See XSS Will be Affected 
![redaktor](https://cloud.githubusercontent.com/assets/8643317/21524897/b1f38572-cd43-11e6-84e8-acaede5e8a16.PNG)

 

 See My Added pic .

**Comment by gopalkumar315** [comment]
I also found the same bug
![screenshot from 2016-12-28 23-05-48](https://cloud.githubusercontent.com/assets/10459847/21527610/7a31fed4-cd52-11e6-957c-242731a20bba.png)

**Comment by redaktorio** [comment]
This is only local to your browsers. We give you complete privilege to use *css / js / html* the way you like.

This can be re-produced through out the app and the whole purpose of the app is to make it as flexible for you to code as possible.

This sort of bug will only happen if you inject XSS yourself, otherwise it won't be there.

**Comment by Sajibekanti** [comment]
Yes , it Meself , But Your Project Name Parameter is Affected , ;)

**Comment by redaktorio** [comment]
doesn't matter for now, bcz it would only effect the people who do it to themselves.

If we have multiple users interacting somehow, only then it matters.
